# Use the httpd-parent image as base
FROM quay.io/zshamim/another-http

LABEL io.openshift.expose-services="8080:http"

RUN sed -i 's/Listen 80/Listen 8080/g' /etc/httpd/conf/httpd.conf 

RUN chgrp -R 0 /var/run/httpd /run/httpd /var/www/ /var/log/httpd /etc/httpd/logs && \
    chmod -R g=u /var/run/httpd /run/httpd /var/www/ /var/log/httpd /etc/httpd/logs


USER 1001 


EXPOSE 8080
